### PR TITLE
Fix "invalid escape sequence" warnings in Python 3.6

### PR DESCRIPTION
**Pull request by timgraham**
http://bugs.python.org/issue27364

### CODE REVIEW

**Comment by timgraham** [comment]
There might be more warnings but I had trouble building it so I could run the test suite:
```
$ python setup.py build
running build
running build_py
copying src/argon2/_password_hasher.py -> build/lib.linux-x86_64-3.7/argon2
copying src/argon2/low_level.py -> build/lib.linux-x86_64-3.7/argon2
warning: build_py: byte-compiling is disabled, skipping.

running build_clib
building 'libargon2' library
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -msse2 -Iextras/libargon2/src/../include -Iextras/libargon2/src/blake2 -c extras/libargon2/src/argon2.c -o build/temp.linux-x86_64-3.7/extras/libargon2/src/argon2.o
gcc: error: extras/libargon2/src/argon2.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
error: command 'gcc' failed with exit status 4
```

**Comment by hynek** [comment]
Thanks I’ll look at it as soon as homebrew gets a pyenv that carries the Beta.

As for the tests, you probably have to run: 

```
git submodule init
git submodule update
```

how could i forget to add that to contributing. :|

**Comment by timgraham** [comment]
Yep, and `pip install -r dev-requirements.txt`. I don't see any more warnings, thanks!

**Comment by hynek** [comment]
JFTR, I’m still waiting for virtualenv to be updated.  :'(

**Comment by hynek** [comment]
Ah screw it, we’ll yolo it in and if there’s still breakage, we’ll fix it later.  thanks!

**Pull request merged**
